apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-mini-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/lixiubao4967/okj-aws-infra.git
        revision: main  # prod 环境跟踪 main 分支
        directories:
          - path: practice/argo-mini/overlays/prod/*

  template:
    metadata:
      name: argo-mini-prod-{{path.basename}}
    spec:
      project: argo-mini-prod

      source:
        repoURL: https://github.com/lixiubao4967/okj-aws-infra.git
        targetRevision: main
        path: practice/argo-mini/overlays/prod/{{path.basename}}

      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
