apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-webhook-config
  namespace: okj-monitor
data:
  config.yaml: |
    server:
      port: 8080
    lark:
      apps:
        firing:
          appid: "test-app-id"
          appsecret: "test-app-secret"
          chatId: "test-chat-id"
        resolved:
          appid: "test-app-id"
          appsecret: "test-app-secret"
          chatId: "test-chat-id"
