apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# dev 环境特化层
# ArgoCD 监听本目录，ApplicationSet 自动创建 Application: argo-mini-dev-redis

resources:
  - ../../../base/redis

images:
  - name: redis
    newTag: "7-alpine"

replicas:
  - name: redis
    count: 1
